### ISSUE TITLE
[feature request] typescript types definition support

### ISSUE THREAD

**Issue by trylovetom** [lucagez/slow-json-stringify#14]
Hello! There will be great to support the typescript types definition. Add the index.d.ts to notation the module type.

**Comment by lucagez** [comment]
Good Idea, just [opened a PR for that](https://github.com/lucagez/slow-json-stringify/pull/15/files) if you want to have a look.
Not sure how to go about defining the type for the sjs `schema`. Any input would be much appreciated

**Comment by lucagez** [comment]
Typings are added in version `2.0.1`
