### ISSUE TITLE
[Feature request]: Default value?

### ISSUE THREAD

**Issue by dalisoft** [lucagez/slow-json-stringify#27]
Hi @lucagez 

Is there any way to set default value if value was not provided? Like `attr('string', 'Lorem ipsum')`?

**Comment by lucagez** [comment]
Yes, you can use a custom serializer for that
```js
attr('string', value => value || 'Lorem Ipsum');
```

**Comment by dalisoft** [comment]
Thanks @lucagez 

Also, i see slow-json-stringify bit slow for **Objects**, is there any way optimize it?

**Comment by lucagez** [comment]
@dalisoft I opened a new issue discussing possible performance optimizations here https://github.com/lucagez/slow-json-stringify/issues/28#issue-886290943. Feel free to leave comments/suggestions there.
