### ISSUE TITLE
Does this work well with flatstr?

### ISSUE THREAD

**Issue by RichardWright** [lucagez/slow-json-stringify#29]
Hi

Does this lib work well with https://www.npmjs.com/package/flatstr ?

**Comment by kurtextrem** [comment]
flatstr has an issue showing that node v12 is equally fast, so I'd say flatstr is redundant.

**Comment by lucagez** [comment]
Yes I can confirm `flatstr` optimizations are introducing a not significant increment in performance. Results are, in my tests not consistently reproducibles. I assume the difference between results should be attributed to the runtime.
A draft PR about `flattened` otpimization + benchmarks can be found here https://github.com/lucagez/slow-json-stringify/pull/32
