### ISSUE TITLE
Is SJS deterministic?

### ISSUE THREAD

**Issue by dimitry12** [lucagez/slow-json-stringify#3]
Is SJS deterministic in the same sense as https://github.com/substack/json-stable-stringify is?

**Comment by lucagez** [comment]
Yes, thanks to its template nature. 
When you compile a schema, SJS will create a template and a queue. So, given two objects with the same props/values, sjs will always outputs two equal strings.

**E.g.**
```javascript
const stringify = sjs({ a: 'string', b: 'number' });

// output template => [ { "a":" ] x1  [ ", "b": ]  x2  [ } ]

stringify({a:"hello",    b: 42    })  // {"a":"hello","b":42}

stringify({b:42,  a:"hello"  })  // {"a":"hello","b":42}
```

The order of the properties inside the object is irrelevant. As the template requires to be filled following the exact queue order. 
In this particular case [a, b]
