### ISSUE TITLE
[acc].flat error : undefined is not a function.

### ISSUE THREAD

**Issue by wkmcyz** [lucagez/slow-json-stringify#5]
This is because the use of `Array.flat` API, which is not supported below node `v11.0.0`.Here is the [Browser Compatibility of Array.flat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#Browser_compatibility). So as far as I am concerned, other implementations here may be better for more scenarios.

**Comment by wkmcyz** [comment]
Actually I want to use sjs in react-native, however it seems that react-native does not support `Array.flat` according to https://stackoverflow.com/a/52878753/9798666.

**Comment by wkmcyz** [comment]
I found a workaround for this, which is to use [array-flat-polyfill](https://github.com/jonathantneal/array-flat-polyfill#readme).

**Comment by lucagez** [comment]
Hi @wkmcyz 👋
Thank you for pointing out this compatibility issue!
I was using [acc].flat() just for its convenient syntax.
I replaced it with an array check with a consequent manual wrapping into an array. As it's a lightweight workaround and it adds zero external dependencies.

Let me know if this fix your issues!

**Comment by wkmcyz** [comment]
Hi @lucagez 😁.
Of course this fixed the issue, thank you for such a great job to write sjs. It's really fast🚀.
